application: jakobdams
version: production
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /static
  static_dir: static

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /uploads
  script: plupload.py 

- url: /.*
  script: main.py
